#pragma once

#include <array>
#include <cstddef>
#include <iterator>
#include <ranges>

#include "pushfold/Combinator.hpp"

namespace pushfold::threeway {

/**
 * @brief A std::ranges view over every way to split N cards into three
 *        unordered two-card hands.
 *
 * A three-way deal is an unordered collection of three disjoint two-card hands
 * (a "multiset" of hands: two — or all three — players can share the same
 * infoset). Each such deal corresponds to exactly one six-card combination
 * together with one partition of those six cards into three unordered pairs, of
 * which there are 6! / (2^3 * 3!) = 15. The view therefore walks the six-card
 * combinations of {0, ..., N-1} in Combinator order and, within each, emits the
 * 15 partitions, so every unordered triple of hands is produced exactly once.
 *
 * Cards are yielded as their indices (like Combinator). Each emitted value is
 * canonical: the two cards within a hand are ascending, and the three hands are
 * ordered by their first card. Degenerate shapes follow the math: N < 6 yields
 * nothing.
 *
 * The view is stateless and its iterators own their state (a Combinator
 * iterator plus a partition index), so they stay valid after the Multiset is
 * destroyed: it is a borrowed_range.
 */
template <size_t N>
class Multiset : public std::ranges::view_interface<Multiset<N>> {
   public:
    static constexpr size_t kGroups = 3;
    static constexpr size_t kGroupSize = 2;
    static constexpr size_t kCards = kGroups * kGroupSize;  // 6

    using Hand = std::array<size_t, kGroupSize>;
    using Deal = std::array<Hand, kGroups>;

    /**
     * @brief The 15 partitions of {0, ..., 5} into three unordered pairs.
     *
     * Generated by pairing the smallest not-yet-used element with each of the
     * remaining elements in turn, so within every pair the indices ascend and
     * the pairs themselves ascend by first element. Because a six-card
     * combination is ascending, applying a partition preserves that canonical
     * ordering in the emitted Deal.
     */
    static constexpr std::array<std::array<size_t, kCards>, 15> kPartitions = {{
        {0, 1, 2, 3, 4, 5},
        {0, 1, 2, 4, 3, 5},
        {0, 1, 2, 5, 3, 4},  //
        {0, 2, 1, 3, 4, 5},
        {0, 2, 1, 4, 3, 5},
        {0, 2, 1, 5, 3, 4},  //
        {0, 3, 1, 2, 4, 5},
        {0, 3, 1, 4, 2, 5},
        {0, 3, 1, 5, 2, 4},  //
        {0, 4, 1, 2, 3, 5},
        {0, 4, 1, 3, 2, 5},
        {0, 4, 1, 5, 2, 3},  //
        {0, 5, 1, 2, 3, 4},
        {0, 5, 1, 3, 2, 4},
        {0, 5, 1, 4, 2, 3},  //
    }};
    static constexpr size_t kNumPartitions = kPartitions.size();

    /**
     * @brief Forward iterator that walks (combination, partition) pairs.
     *
     * The state is a Combinator<N, 6> iterator and an index into kPartitions.
     * Both are owned by value, so copies are independent and the multipass
     * guarantee holds. The current Deal is materialized on dereference, so the
     * reference type is a prvalue (as with iota_view); operator-> is therefore
     * not provided.
     */
    class Iterator {
       public:
        using value_type = Deal;
        using reference = Deal;
        using difference_type = std::ptrdiff_t;
        using iterator_concept = std::forward_iterator_tag;
        // A prvalue reference caps the legacy category at input; iterator_concept
        // carries the true forward capability for the std::ranges machinery.
        using iterator_category = std::input_iterator_tag;

        /// Constructs a past-the-end iterator.
        Iterator() = default;

        reference operator*() const {
            const std::array<size_t, kCards>& cards = *combo_;
            const std::array<size_t, kCards>& p = kPartitions[partition_];
            return Deal{{
                Hand{cards[p[0]], cards[p[1]]},
                Hand{cards[p[2]], cards[p[3]]},
                Hand{cards[p[4]], cards[p[5]]},
            }};
        }

        Iterator& operator++() {
            Advance();
            return *this;
        }

        Iterator operator++(int) {
            Iterator previous = *this;
            Advance();
            return previous;
        }

        bool operator==(const Iterator& other) const {
            // The Combinator iterator handles its own past-the-end comparison; an
            // exhausted iterator always carries partition_ == 0 (see Advance), so
            // the two end iterators still compare equal.
            return combo_ == other.combo_ && partition_ == other.partition_;
        }

       private:
        friend class Multiset;

        explicit Iterator(typename Combinator<N, kCards>::Iterator combo) : combo_(combo) {}

        /// Advances to the next partition, rolling over to the next six-card
        /// combination once all 15 have been emitted. When the underlying
        /// combinations are exhausted, combo_ becomes past-the-end with
        /// partition_ back at 0, matching the end iterator.
        void Advance() {
            ++partition_;
            if (partition_ == kNumPartitions) {
                partition_ = 0;
                ++combo_;
            }
        }

        typename Combinator<N, kCards>::Iterator combo_{};
        size_t partition_ = 0;
    };

    Iterator begin() const { return Iterator(Combinator<N, kCards>{}.begin()); }
    Iterator end() const { return Iterator(Combinator<N, kCards>{}.end()); }

    /// Number of deals in the view: C(N, 6) six-card combinations, each split 15
    /// ways (zero when N < 6). Makes Multiset a sized_range.
    static constexpr size_t size() { return Combinator<N, kCards>::size() * kNumPartitions; }
};

}  // namespace pushfold::threeway

// The iterators own their state and never refer back to the Multiset, so a deal
// obtained from a temporary Multiset stays valid: it is a borrowed_range.
template <size_t N>
inline constexpr bool std::ranges::enable_borrowed_range<pushfold::threeway::Multiset<N>> = true;
